### ISSUE TITLE
Can buildmer operate with mixed effect models in Julia?

### ISSUE THREAD

**Issue by liamblything1** [cvoeten/buildmer#12]
Hello, I've recently started running lmer via Julia because it affords more complex models to converge more easily than R.

Note that this is still on the R interface but I call Julia and then use the Julia package #j$library("MixedModels")

My Question is: is it possible to use buildmer for Julia-run mixed effect models? And if so, how would I go about it?

Thank you,
Liam

**Comment by cvoeten** [comment]
Yes, this is possible. You would need to use `buildcustom()`, and write your own `fit` and `crit` functions that perform the appropriate operations through JuliaCall. In previous versions of buildmer, these were in fact implemented and made available through function `buildjulia()`, but I removed it all due to the large maintenance burden (these functions required a LOT of special-casing throughout buildmer because JuliaCall cannot work with standard R generics). You might look through the code for buildmer v1.5 to see if you can still use them as a starting point in your endeavors.

Closing NOTABUG as `buildjulia()` was removed on purpose and doing the legwork yourself via `buildcustom()` is the way to go. Good luck!
