### ISSUE TITLE
buildcustom() vignettes

### ISSUE THREAD

**Issue by phliulei** [cvoeten/buildmer#4]
Sorry to bother you. I want to use afex to find the maximal feasible model, and i wonder how to use buildcustom() to do it? As you said

> 'yes, you can use buildmer with any fitting engine you like via buildcustom()'

**Comment by cvoeten** [comment]
Yes, `buildcustom` could probably use a vignette of its own. Unfortunately, this is low on my to-do list. But you should be able to get going from `?buildcustom`. Basically, the idea is that you provide your own `fit` function, which returns a fitted model object. You can then use the buildmer `crit` functions (e.g. `crit='LRT'`, which translates to `crit=buildmer:::crit.LRT`) or write your own. This is called on individual fitted model objects to determine which of many competing models is best in the order step. You should similarly specify an `elim` function, which is used by the forward and backward steps to do pairwise comparisons of a reference model and an alternative model, which gives you the likelihood-ratio-test statistic, or the delta-AIC, etc etc. See the example for `buildcustom` for a template of sorts.

I will leave the issue open as I should at some point write a vignette.

**Comment by phliulei** [comment]
Thanks， let me have a try.

**Comment by cvoeten** [comment]
I'm sorry, but I'll be realistic - I'm just not going to write a vignette for `buildcustom`, as the 2+ years of lack of activity on this issue may have suggested. `buildcustom` is tied very tightly to buildmer's internals, such that if you really need a vignette, you're probably also in need of a simpler solution altogether. Sorry - part of the problem is also that I simply don't have the time, but I think this is also an important consideration; if you need a vignette for this, this is not the tool for you.
