### ISSUE TITLE
It seems that `select = T` is not working on `buildgam`

### ISSUE THREAD

**Issue by guilhermeparreira** [cvoeten/buildmer#9]
See:
```
dmaster <- structure(list(TempodeProva = c(778.433333333333, 798.816666666667, 
                                           802.416666666667, 898.583333333333, 898.583333333333, 913.733333333333, 
                                           1002.25, 1084.91666666667, 1094.91666666667, 1132.55, 1141.48333333333, 
                                           1141.5, 1190.41666666667, 1210.51666666667, 1217.46666666667, 
                                           1219.71666666667, 1230.6, 1248.95, 1260.51666666667, 1283.46666666667, 
                                           1283.83333333333, 1309.16666666667), Ca = c(-0.28, -0.18, 0.36, 
                                                                                       -0.21, -0.53, -0.03, -0.0899999999999999, -0.11, -0.1, -0.11, 
                                                                                       -0.0700000000000001, 0.01, -0.05, -0.13, -0.1, -0.0700000000000001, 
                                                                                       -0.0800000000000001, -0.12, -0.12, -0.0700000000000001, 0.02, 
                                                                                       -0.12), Wtr = c(-0.399999999999999, -1.1, -0.200000000000003, 
                                                                                                       2.1, -1.4, -0.800000000000004, -47.3, -32.1, -1.8, -39.2, -1.90000000000001, 
                                                                                                       -1.3, 1.5, 1.1, -1.7, 1.9, 0.800000000000004, -3, 3.1, -0.399999999999999, 
                                                                                                       -1.40000000000001, 0.100000000000001)), class = "data.frame", row.names = c(NA, 
                                                                                                                                                                                   -22L))
 m2 <- buildgam(TempodeProva ~ 1 + s(Ca) + s(Wtr), 
                direction = "forward",
                data = dmaster, 
                quiet = T,
                family = Gamma(link = "log"))
 m2 <- m2@model
 summary(m2)

Family: Gamma 
Link function: log 

Formula:
TempodeProva ~ 1 + s(Ca) + s(Wtr)

Parametric coefficients:
            Estimate Std. Error t value Pr(>|t|)    
(Intercept)     6.99       0.02     349   <2e-16 ***
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Approximate significance of smooth terms:
        edf Ref.df    F p-value    
s(Ca)  4.62   5.36 8.79 0.00043 ***
s(Wtr) 1.00   1.00 3.65 0.07523 .  
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

R-sq.(adj) =  0.634   Deviance explained = 74.7%
-REML = 146.89  Scale est. = 0.0088165  n = 22
m2 <- gam(TempodeProva ~ 1 + s(Ca) + s(Wtr), 
           select = T,
                data = dmaster, 
                family = Gamma(link = "log"))
 summary(m2)

Family: Gamma 
Link function: log 

Formula:
TempodeProva ~ 1 + s(Ca) + s(Wtr)

Parametric coefficients:
            Estimate Std. Error t value Pr(>|t|)    
(Intercept)  6.98807    0.00972     719   <2e-16 ***
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Approximate significance of smooth terms:
         edf Ref.df     F   p-value    
s(Ca)  8.857      9 30.72 0.0000041 ***
s(Wtr) 0.864      9  1.04    0.0069 ** 
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

R-sq.(adj) =  0.907   Deviance explained = 95.9%
GCV = 0.0040676  Scale est. = 0.0020795  n = 22
```

Am I missing something?

**Comment by cvoeten** [comment]
I don't understand what the issue is. Your first model does not include `select=TRUE`. Your second model does include it, but is fitted using `gam`, not `buildgam` (and using GCV rather than REML), so doesn't involve `buildgam`. What are you trying to do? I do indeed get different results with
```
 m2 <- buildgam(TempodeProva ~ 1 + s(Ca) + s(Wtr), 
                direction = "forward",
                data = dmaster, 
                quiet = T,
                family = Gamma(link = "log"),
                select=TRUE)
```
than without `select=TRUE`, so it does seem to be working just fine.

**Comment by guilhermeparreira** [comment]
Thank you for your answer! I will clarify my points:

+ I thought that `buildgam` would use the same default method to estimate a model as `gam`. But they don't. While `buildgam` uses `REML` for `gam` models, gam uses `GCV.Cp`.
+ I misunderstood the `buildgam` docummentation. I thought that `select = T` was the default option for `gam` model. I just read more carefully, and `select` is set to `TRUE` only for `cox.ph` family. 

Sorry for that. Given these considerations, a possible issue is presented here:

m20 <- buildgam(TempodeProva ~ 1 + s(Ca) + s(Wtr), 
               direction = "backward",
               data = dmaster, 
               crit = "LRT",
               quiet = T,
               select = T,
               method = "REML",
               family = Gamma(link = "log"))
# It returns no model
But if I do the same manually, I get that `Ca` has a significant effect:
m21 <- gam(TempodeProva ~ 1 + s(Ca) + s(Wtr), 
          select = T,
          method = "REML",
          data = dmaster, 
          family = Gamma(link = "log"))
m22 <- gam(TempodeProva ~ 1 + s(Wtr), 
           select = T,
           method = "REML",
           data = dmaster, 
           family = Gamma(link = "log"))
anova(m21, m22, test = "Chisq")
Analysis of Deviance Table

Model 1: TempodeProva ~ 1 + s(Ca) + s(Wtr)
Model 2: TempodeProva ~ 1 + s(Wtr)
  Resid. Df Resid. Dev    Df Deviance Pr(>Chi)    
1      15.3      0.216                            
2      21.0      0.579 -5.66   -0.363 0.000022 ***
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

The same type of problem occurs if I change the criteria to `AIC` in `buildgam`. So I don't think that the variable selection is consistent for gam models, or I am missing something else.

However, what I really want to do is: make variable selection with `REML` method and `select=T` looking for the `p-values` of `summary(model)` output, as it is [suggested by Gavin Simpson](https://stats.stackexchange.com/questions/274151/anova-to-compare-models). I am not sure if I can do this using your package (I don't which option should I use for `crit` argumment. 
 
Thank you again!!!

**Comment by guilhermeparreira** [comment]
Thank you for your answer! I will clarify my points:

+ I thought that `buildgam` would use the same default method to estimate a model as `gam`. But they don't. While `buildgam` uses `REML` for `gam` models, gam uses `GCV.Cp`.
+ I misunderstood the `buildgam` docummentation. I thought that `select = T` was the default option for `gam` model. I just read more carefully, and `select` is set to `TRUE` only for `cox.ph` family. 

Sorry for that. Given these considerations, a possible issue is presented here:

m20 <- buildgam(TempodeProva ~ 1 + s(Ca) + s(Wtr), 
               direction = "backward",
               data = dmaster, 
               crit = "LRT",
               quiet = T,
               select = T,
               method = "REML",
               family = Gamma(link = "log"))
# It returns no model
But if I do the same manually, I get that `Ca` has a significant effect:
m21 <- gam(TempodeProva ~ 1 + s(Ca) + s(Wtr), 
          select = T,
          method = "REML",
          data = dmaster, 
          family = Gamma(link = "log"))
m22 <- gam(TempodeProva ~ 1 + s(Wtr), 
           select = T,
           method = "REML",
           data = dmaster, 
           family = Gamma(link = "log"))
anova(m21, m22, test = "Chisq")
Analysis of Deviance Table

Model 1: TempodeProva ~ 1 + s(Ca) + s(Wtr)
Model 2: TempodeProva ~ 1 + s(Wtr)
  Resid. Df Resid. Dev    Df Deviance Pr(>Chi)    
1      15.3      0.216                            
2      21.0      0.579 -5.66   -0.363 0.000022 ***
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

The same type of problem occurs if I change the criteria to `AIC` in `buildgam`. So I don't think that the variable selection is consistent for gam models, or I am missing something else.

However, what I really want to do is: make variable selection with `REML` method and `select=T` looking for the `p-values` of `summary(model)` output, as it is [suggested by Gavin Simpson](https://stats.stackexchange.com/questions/274151/anova-to-compare-models). I am not sure if I can do this using your package (I don't which option should I use for `crit` argumment. 
 
Thank you again!!!

**Comment by cvoeten** [comment]
If you remove your `quiet=T`, you'll see that `buildgam` is failing to do anything because
```
Error in (function (formula, family = gaussian(), data = list(), weights = NULL,  : 
  formal argument "method" matched by multiple actual arguments
```
which is correct: `buildgam` decides whether to fit using ML and REML and adds this as an argument, which conflicts with your own `method` argument. If you want to unconditionally fit using REML, use `buildmerControl=list(REML=TRUE)` instead to instruct buildmer to not make its own decision but always use REML.

If you want to use AIC for model comparisons, as Gavin Simpson does at the end of his answer, you can just pass `crit='AIC'` in `buildmerControl`.

I still don't think there's a bug in buildmer here, but please reopen if I'm wrong.

**Comment by guilhermeparreira** [comment]
Thank you for your advice! I made the correction, but I still don't agree with the results. See:

```
# I am forcing REML to make things comparable:
m20 <- buildgam(TempodeProva ~ 1 + s(Ca) + s(Wtr), 
               direction = "backward",
               data = dmaster, 
               crit = "LRT",
               quiet = F,
               select = T,
               family = Gamma(link = "log"),
               buildmerControl = list(REML = T))
Fitting REML reference model
Fitting via gam, with REML: TempodeProva ~ 1 + s(Ca) + s(Wtr)
Testing terms
Fitting via gam, with REML: TempodeProva ~ 1 + s(Wtr)
Fitting via gam, with REML: TempodeProva ~ 1 + s(Ca)
  grouping   term        block Iteration        LRT
1       NA      1      NA NA 1         1         NA
2       NA  s(Ca)  NA NA s(Ca)         1 0.00031629
3       NA s(Wtr) NA NA s(Wtr)         1        NaN
All terms are significant
Warning message:
In stats::pchisq(chLL, chdf - 1, lower.tail = FALSE, log.p = TRUE) :
  NaNs produced
```

 I quite don't understand the message that says that terms are significant, but it shows `NaN` for `LRT` for `Wtr`. Moreover, the p-value is NaNs which it is strange. The summary contains all covariates ( I just included the important bit):
``` 
> summary(m20)
Approximate significance of smooth terms:
         edf Ref.df    F p-value    
s(Ca)  3.577      9 3.16 0.00071 ***
s(Wtr) 0.273      9 0.04 0.25014    
```

It shows that Wtr is not significant (I would like to make the variable selection via the p-value from summary, which it is another topic - Can also I do this with your package?). Continuing with the question... Reproducing a backward LRT by hand I conclude that Wtr is not significant:

```
m21 <- gam(TempodeProva ~ 1 + s(Ca) + s(Wtr), 
          select = T,
          method = "REML",
          data = dmaster, 
          family = Gamma(link = "log"))
m22 <- gam(TempodeProva ~ 1 + s(Ca), 
           select = T,
           method = "REML",
           data = dmaster, 
           family = Gamma(link = "log"))
# summary(m21)
anova(m21, m22, test = "Chisq")
Analysis of Deviance Table

Model 1: TempodeProva ~ 1 + s(Ca) + s(Wtr)
Model 2: TempodeProva ~ 1 + s(Ca)
  Resid. Df Resid. Dev     Df Deviance Pr(>Chi)
1      15.3      0.216                         
2      16.2      0.233 -0.854  -0.0175     0.19
```

Why does `Wtr` have a significant effect on the model fitted by `buildgam`?

**Comment by cvoeten** [comment]
buildmer approaches GAMs, from a model-comparison perspective, as mixed-effects models. When you fit using `select=TRUE`, your smooth terms do not have a fixed-effects component in this formulation, only a random-effects component. Per Stram & Lee (1994), the H0 in a comparison of models differing only in random effects is not chi-square-distributed, but is an equal mixture of a chisq(n) and chisq(n-1) distribution. `anova` does not take this into account, hence why its results are as they are (and are slightly biased). buildmer does take this into account (see the code in `crit.LRT`), but because the difference in df is <1, when it computes the chisq(n-1) distribution it actually ends up with negative df, in which case the chi-squared distribution is not defined, hence the NaN.

You might argue that this result is not correct, and that I should do something about it (e.g. clamp the df to always be >=0?). But I don't know if that is warranted; at least, I haven't been able to find any literature that suggests how one should act in this case while maintaining the inferential properties of the likelihood-ratio test (beyond 'use simulation', which is of course always the best answer). As such, I believe the NaN result is actually correct, in that it adequately reflects that it is unknown what the correct answer should be in this case. buildmer then, too, doesn't know what to do with this result, and therefore takes the safe option of concluding that this term is evidently not eligible for removal. I think this, too, is the correct choice in this case.

Should you know of a paper describing the distribution to use when testing random effects with <1 difference in df, please by all means do point me to it! And do note that this issue is specific to likelihood-ratio testing; if you use another criterion, such as AIC, the chi-square distribution never comes into play.

**Comment by guilhermeparreira** [comment]
Hum. I understand now why! (I didn't know that when `select = T` everything becomes R.E.)
Thank you mate! For `AIC` I indeed obtain comparable results.

Last question on this topic:
+ Is there a possibility to implement (or is it already available) the variable selection only for `buildgam` based on summary p-values:
![image](https://user-images.githubusercontent.com/13880005/110993388-fb822000-8355-11eb-8f78-e4700c55daca.png)

In this case, `Wtr` would be removed, and Ca would stay in the model.

**Comment by cvoeten** [comment]
This is not implemented natively, because it kind of goes against the architecture that buildmer uses. All criteria that are implemented in buildmer compare two models with one another, rather than looking at the summary of only one model. However, it does make sense that in this case you would want to do this, and it is possible. All buildmer functions accept arbitrary `crit` functions; see the help for `buildcustom` for where this comes from, but note that the details are not well-documented because this simply isn't a popular feature.

In brief, you need to write your own `crit` function that looks like:
```
mycrit <- function (p,cur,alt) {
......
}
```
and returns some kind of score. This function would take the `alt` model (which is the larger one of the two) and return the single relevant p-value (this may be a bit harder than you think, because given two arbitrary models `cur` and `alt`, you need to figure out which p-value from the summary is the one you want! So you would somehow need to find the single row in the two models' summaries that is different between them). You would then also need your own `elim` function, which I think can just be this:
```myelim <- function (p) p >= .05```
Then in `buildmerControl`, say `crit=mycrit` and `elim=myelim`. That ought to do it.

**Comment by cvoeten** [comment]
I've given this issue some further thought and I came to the following conclusion. Stram & Lee's correction is based on the assumption that a comparison between two models differing only in N random-effect terms will be considered to differ in N df, where 'a random-effect term' is interpreted as in lme4. They show that under this assumption, the actual distribution of the chi-square test statistic is not chisq(N) but rather a combination of chisq(N) and chisq(N-1). However, GAMs as implemented in mgcv do not in fact make this assumption: they instead define the difference in df empirically based on the trace of the hat matrix. This is precisely why mgcv df differences can be fractional, while lme4 df differences will always be integer. As such, I now believe that Stram & Lee's argument was never meant to cover the case of GAMs, which use an entirely different approach to dfs, and therefore shouldn't be applied after all.

So, I've now pushed an update to main that disables this correction for GAMs, more specifically for models that do not differ exclusively in lme4-style random-effect terms.

However, this still does not produce the same results as manually calling `anova()` on two gam objects. I don't know why; I'm getting my dfs in the usual way, namely from `df` attribute of the models' `logLik()`s, which it seems is the same thing as the `sum`s of their `$edf2`s - as it should be! - but a manual `anova()` with two GAM models ends up with a different df difference, of which I don't see where it's coming from.

Any suggestions (from anyone, I'm not specifically addressing the original reporter) where this difference is coming from would be appreciated. I'm getting the df in a principedly correct way, so I believe that the different results between `buildgam()` and `anova()` are simply _differences_, rather than one being right and the other being wrong, but I'd still be interested in learning what is going on.

**Comment by cvoeten** [comment]
I've now pushed another update that will just call `anova` on two GAM models and use that p-value, rather than attempting to compute it myself from the `logLik's.

**Comment by cvoeten** [comment]
Never mind, issue now seems to be solved completely, meaning that with the latest GitHub version you can use likelihood ratio tests and they will do the right thing. Thanks again for bringing this issue to my attention and getting me to further think about these issues again!

**Comment by guilhermeparreira** [comment]
Hi @cvoeten !
I managed to make a function that takes two model, and return a single p-value from `summary` as you suggested. What I don't know is how to create the `fit` and `formula` function. Could you have a look/provide some guidance?
See my work:

```
myelim <- function(p) p>= .05
dmasterm1 <- structure(list(BMI = c(-0.599999999999998, -0.400000000000002, 
                                    -0.199999999999999, -0.300000000000001, -0.899999999999999, -0.699999999999999, 
                                    -4.4, -0.699999999999999, -0.5, 0.100000000000001, -0.800000000000001, 
                                    -0.800000000000001, -0.5, -1.2, -0.899999999999999, -1.2, -0.300000000000001, 
                                    -0.800000000000001, 0.800000000000001, -1, -0.5, -0.599999999999998
), BMR = c(-10, -27, -5, 48, -31, -20, -172, -50, -41, 19, -45, 
           -31, 34, 25, -40, 45, 19, -71, 88, -10, -35, 27), Alfa3 = structure(c(2L, 
                                                                                 1L, 2L, 1L, 3L, 1L, 3L, 1L, 2L, 1L, 2L, 2L, 2L, 3L, 2L, 2L, 2L, 
                                                                                 2L, 2L, 3L, 3L, 2L), .Label = c("RR", "RX", "XX"), class = "factor"), 
Ca = c(-0.28, -0.18, -0.0800000000000001, -0.21, -0.53, -0.03, 
       -0.0899999999999999, -0.11, -0.1, -0.11, -0.0700000000000001, 
       0.01, -0.05, -0.13, -0.1, -0.0700000000000001, -0.0800000000000001, 
       -0.12, -0.12, -0.0700000000000001, 0.02, -0.12)), class = "data.frame", row.names = c(NA, 
                                                                                             -22L))
mycrit <- function (p=NULL,cur=NULL,alt) {
  sm <- summary(alt)
  dalt <- data.frame(Terms=c(row.names(sm$s.table),
                             row.names(sm$p.table)),
                     p= c(sm$s.pv, sm$p.pv))
  ss <- summary(cur)
  dcur <- data.frame(Terms=c(row.names(ss$s.table),
                             row.names(ss$p.table)),
                     p= c(ss$s.pv, ss$p.pv))
  
  p <- min(dalt[!dalt$Terms %in%  dcur$Terms, 2])
  return(p)
}
#Alt is the bigger model
m2 <- gam(TempodeProva ~ 1 + s(BMI) + s(BMR), 
          data = dmasterm, 
          family = Gamma(link = "log"))
m20 <- gam(TempodeProva ~ 1 + s(BMR), 
           data = dmasterm, 
           family = Gamma(link = "log"))
# summary(m2)
mycrit(cur=m20, alt = m2)
[1] 0.1350039
m2 <- gam(TempodeProva ~ 1 + Alfa3 + s(BMR), 
          data = dmasterm, 
          family = Gamma(link = "log"))
m20 <- gam(TempodeProva ~ 1 + s(BMR), 
           data = dmasterm, 
           family = Gamma(link = "log"))
# summary(m2)
mycrit(cur=m20, alt = m2)
[1] 0.03023054
m2 <- gam(TempodeProva ~ 1 + s(Ca) + s(BMR), 
          data = dmasterm, 
          family = Gamma(link = "log"))
m20 <- gam(TempodeProva ~ 1 + s(BMR), 
           data = dmasterm, 
           family = Gamma(link = "log"))
# summary(m2)
mycrit(cur=m20, alt = m2)
[1] 0.032339
# how to use it here?
m2 <- buildgam(TempodeProva ~ 1 + s(BMR) + s(Ca) + Alfa3 + s(BMI), 
               direction = "forward",
               data = dmasterm, 
               # crit = "LRT",
               quiet = F,
               select = T,
               family = Gamma(link = "log"),
               buildcustom(crit = mycrit,
                           elim = myelim))
```

Thanks!!

**Comment by cvoeten** [comment]
You can just reuse `buildmer:::fit.gam`. This should do it --- but I can't test whether it actually works because I don't have `dmasterm` and your `dmaster1` is missing the dependent variable.
```
buildcustom(TempodeProva ~ 1 + s(BMR) + s(Ca) + Alfa3 + s(BMI),buildmerControl=list(fit=buildmer:::fit.gam,crit=mycrit,elim=myelim,family=Gamma(link=log),data=dmasterm,direction='forward',quiet=FALSE,dots=list(select=TRUE)))
```
Note that your custom criterion won't work for the ordering step because that expects your `crit` to return values such that lower = better, but this is no problem for you because you specify `direction='forward'`.

Finally, though, now that I've changed the way degrees of freedom are handled by `buildgam`, you may prefer the default likelihood-ratio tests after all! But that is up to you, of course.

**Comment by guilhermeparreira** [comment]
Thank you cvoeten!

I was still considering to look at the `p-values` from `summary` because Simon suggest it in the link that I provided to you sometime before... They don't suggest using `anova`. That's why (or I am missing something).

My code didn't work: it still selected a smooth therm non significant:

```
dmasterm <- structure(list(TempodeProva = c(778.433333333333, 798.816666666667, 
802.416666666667, 898.583333333333, 898.583333333333, 913.733333333333, 
1002.25, 1084.91666666667, 1094.91666666667, 1132.55, 1141.48333333333, 
1141.5, 1190.41666666667, 1210.51666666667, 1217.46666666667, 
1219.71666666667, 1230.6, 1248.95, 1260.51666666667, 1283.46666666667, 
1283.83333333333, 1309.16666666667), BMI = c(-0.599999999999998, 
-0.400000000000002, -0.199999999999999, -0.300000000000001, -0.899999999999999, 
-0.699999999999999, -4.4, -0.699999999999999, -0.5, 0.100000000000001, 
-0.800000000000001, -0.800000000000001, -0.5, -1.2, -0.899999999999999, 
-1.2, -0.300000000000001, -0.800000000000001, -0.899999999999999, 
-1, -0.5, -0.599999999999998), BMR = c(-10, -27, -5, 48, -31, 
-20, -172, -50, -41, 19, -45, -31, 34, 25, -40, 45, 19, -71, 
88, -10, -35, 27), Alfa3 = structure(c(2L, 1L, 2L, 1L, 3L, 1L, 
3L, 1L, 2L, 1L, 2L, 2L, 2L, 3L, 2L, 2L, 2L, 2L, 2L, 3L, 3L, 2L
), .Label = c("RR", "RX", "XX"), class = "factor"), Ca = c(-0.28, 
-0.18, -0.0800000000000001, -0.21, -0.53, -0.03, -0.0899999999999999, 
-0.11, -0.1, -0.11, -0.0700000000000001, 0.01, -0.05, -0.13, 
-0.1, -0.0700000000000001, -0.0800000000000001, -0.12, -0.12, 
-0.0700000000000001, 0.02, -0.12)), class = "data.frame", row.names = c(NA, 
-22L))
myelim <- function(p) p>= .05
mycrit <- function (p=NULL,cur=NULL,alt) {
  sm <- summary(alt)
  dalt <- data.frame(Terms=c(row.names(sm$s.table),
                             row.names(sm$p.table)),
                     p= c(sm$s.pv, sm$p.pv))
  ss <- summary(cur)
  dcur <- data.frame(Terms=c(row.names(ss$s.table),
                             row.names(ss$p.table)),
                     p= c(ss$s.pv, ss$p.pv))
  
  p <- min(dalt[!dalt$Terms %in%  dcur$Terms, 2])
  return(p)
}
library(buildmer)
m1f <- buildcustom(TempodeProva ~ s(BMR) + s(Ca) + Alfa3 + s(BMI),
            buildmerControl=list(fit=buildmer:::fit.gam,
                            crit=mycrit,
                            elim=myelim,
                            family=Gamma(link=log),
                            data=dmasterm,
                            direction='forward',
                            quiet=FALSE,
                            dots=list(select=TRUE)))
summary(m1f)
Approximate significance of smooth terms:
         edf Ref.df     F p-value   
s(BMR) 0.616      9 0.197   0.107   
s(Ca)  1.797      9 1.303   0.006 **
```

**Comment by cvoeten** [comment]
This is forward selection working as intended. When I run your code, `s(BMR)` has a p-value of 3.084966e-36 at the time when it is entered into the model. By definition, forward selection will not reevaluate this value when more terms have been added; for that, you would need backward selection. With `direction='backward'`, all terms indeed reach significance.
